fix: Add missing importlib.util import
* Without first importing importlib.util an AttributeError will be raised

```
Traceback (most recent call last):
  File "/madanalysis5/./bin/ma5", line 51, in <module>
    if not importlib.util.find_spec("six"):
           ^^^^^^^^^^^^^^
AttributeError: module 'importlib' has no attribute 'util'
```